curl --request POST http://127.0.0.1:5000/observations/add_observations_json \
--header "Content-Type: application/json" \
--data '{
    "observation_id": "TESTING",
    "observation_date": "2024-11-22",
    "observation_time": "14:30:00",
    "observation_timeZone": "UTC",
    "observation_coordinates": "52.5200, 13.4050",
    "observation_waterTemp": 15.5,
    "observation_airTemp": 20.0,
    "observation_humidity": 75,
    "observation_windSpeed": 5.0,
    "observation_windDirection": "N",
    "observation_precipitation": 10,
    "observation_haze": 0.3,
    "observation_becquerel": 120
}'

curl --request GET http://127.0.0.1:5000/observations/get_observations

curl --request GET http://127.0.0.1:5000/observations/get_one_observation/TEST

curl --request GET http://127.0.0.1:5000/observations/get_one_observation?observation_id=OBS001

curl --request GET http://127.0.0.1:5000/observations/get_one_observation_json \
--header "Content-Type: application/json" \
--data
'{
    "observation_id" : "OBS001"
}'

curl --request DELETE http://127.0.0.1:5000/observations/delete_one_observation/OBS001

curl --request PUT http://127.0.0.1:5000/observations/update_observation/TESY \
--header "Content-Type: application/json" \
--data '{
    "observation_id": "TEST",
    "observation_date": "2024-11-22",
    "observation_time": "14:30:00",
    "observation_timeZone": "UTC",
    "observation_coordinates": "52.5200, 13.4050",
    "observation_waterTemp": 15.5,
    "observation_airTemp": 20.0,
    "observation_humidity": 75,
    "observation_windSpeed": 5.0,
    "observation_windDirection": "N",
    "observation_precipitation": 10,
    "observation_haze": 0.3,
    "observation_becquerel": 120
}'

curl --request PATCH http://127.0.0.1:5000/observations/patch_one_observation/TESTERROR \
--header "Content-Type: application/json" \
--data '{
    "observation_id": "NEWTEST"
}'


curl --request PATCH http://127.0.0.1:5000/observations/patch_one_observation_date/NEWTEST \
--header "Content-Type: application/json" \
--data '{
    "observation_date": "2024-01-11"
}'

curl --request PATCH http://127.0.0.1:5000/observations/patch_one_observation_windspeed/NEWTEST \
--header "Content-Type: application/json" \
--data '{
    "observation_windSpeed": "10"
}'